### GET pro
GET https://mytopnest-production.up.railway.app/webhooks


### GET local
GET http://localhost:3003/webhooks


#### Getend
GET https://eodhd.com/api/eod/AAA.VN?api_token=693e5efda56137.54562069&fmt=json
