### 
@rootUrl = http://localhost:3000
# @rootUrl = https://topmaga.adaptable.app

###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/top-manga/story-lists'

###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/top-manga/story-lists/Murim-Rpg-Simulation'

###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/top-manga/story-lists/Bj-Archmage'

###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/top-manga/mangas/Bj-Archmage/chapter-2'

@test = https://eleceed-default-rtdb.firebaseio.com/prod/eyJhbGciOiJSUzI1NiIsImtpZCLLII6ImE2YzYzNTNm/eleceed/chapter-1.json
###Get pageViolation
curl --location '{{rootUrl}}/top-manga/eleceed/pageViolation'

###Get maxlength
curl --location '{{rootUrl}}/top-manga/eleceed/maxlength'
###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/top-manga/eleceed/1'