### 
@rootUrl = http://localhost:3000
# @rootUrl = https://my-top-nest.vercel.app

###Get all story-lists details
curl --location '{{rootUrl}}/top-manga/story-lists?page=mangas'

###Get story-lists Astral-Pet-Store
curl --location '{{rootUrl}}/top-manga/story-lists/Astral-Pet-Store?page=mangas'


###Get story-lists eleceed
curl --location '{{rootUrl}}/top-manga/story-lists/eleceed?page=mangas'

###Get story-lists eleceed chapter
curl --location '{{rootUrl}}/top-manga/eleceed/294'

###Get story-lists eleceed detail
curl --location '{{rootUrl}}/top-manga/eleceed/0-info'

###Get ip
curl --location '{{rootUrl}}/top-manga/ip'

###Get check auth
curl --location '{{rootUrl}}/top-manga/auth'

###Get 
curl --location 'http://localhost:3000/top-manga/Bj-Archmage/maxlength'

###Post block user
curl --location 'http://localhost:3000/top-manga/userviews/Bj-Archmage/1' \
--header 'Content-Type: application/json' \
--data '{
    "uuid":"hdfadsfasdi"
}'

###Post block user
curl --location '{{rootUrl}}/top-manga/userviews/eleceed/1' \
--header 'Content-Type: application/json' \
--data '{
    "uuid":"hdfadsfasdi"
}'